import { useEffect, useRef, useState } from "react"
import { File as FileIcon, Image, Mic, Paperclip, RotateCcw, Square, Video } from "lucide-react"

import { Button } from "@/components/ui/button"
import { canRecordChatAudio, createAttachmentDraft, logAttachmentFileDiagnostics, normalizeMimeType, setChatPreferredKind, setChatRecordingDuration, validateChatAttachment } from "@/lib/chatMedia"

interface ChatAttachmentPickerProps { disabled?: boolean; onSelect: (file: File, metadata?: { duration: number }) => void; onError: (message: string) => void }
type RecordingState = "idle" | "recording" | "recorded"

function extensionForMime(mime: string): string { if (mime.includes("ogg")) return "ogg"; if (mime.includes("mp4")) return "m4a"; if (mime.includes("mpeg")) return "mp3"; if (mime.includes("wav")) return "wav"; return "webm" }

export function ChatAttachmentPicker({ disabled = false, onSelect, onError }: ChatAttachmentPickerProps) {
  const rootRef = useRef<HTMLDivElement>(null); const imageInput = useRef<HTMLInputElement>(null); const fileInput = useRef<HTMLInputElement>(null); const videoInput = useRef<HTMLInputElement>(null)
  const recorderRef = useRef<MediaRecorder | null>(null); const streamRef = useRef<MediaStream | null>(null); const chunksRef = useRef<Blob[]>([]); const previewUrlRef = useRef<string | null>(null)
  const [menuOpen, setMenuOpen] = useState(false); const [recordingState, setRecordingState] = useState<RecordingState>("idle"); const [seconds, setSeconds] = useState(0); const [recordedFile, setRecordedFile] = useState<File | null>(null); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [dragging, setDragging] = useState(false)
  const stopTracks = () => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null }
  const clearRecording = () => { if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current); previewUrlRef.current = null; chunksRef.current = []; setRecordedFile(null); setPreviewUrl(null); setSeconds(0); setRecordingState("idle") }
  useEffect(() => () => { if (recorderRef.current?.state === "recording") recorderRef.current.stop(); stopTracks(); if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current) }, [])
  useEffect(() => { const reset = () => { if (recorderRef.current?.state === "recording") recorderRef.current.stop(); stopTracks(); clearRecording() }; window.addEventListener("chat-attachment-reset", reset); return () => window.removeEventListener("chat-attachment-reset", reset) }, [])
  useEffect(() => { if (recordingState !== "recording") return; const timer = window.setInterval(() => setSeconds((value) => value + 1), 1000); return () => window.clearInterval(timer) }, [recordingState])
  useEffect(() => { if (recordingState === "recording" && seconds >= 120 && recorderRef.current?.state === "recording") recorderRef.current.stop() }, [recordingState, seconds])
  const pick = (file: File | undefined) => { if (!file) return; try { logAttachmentFileDiagnostics("selected", file); const draft = createAttachmentDraft(file); logAttachmentFileDiagnostics("draft", file, { kind: draft.kind, name: draft.name, mime: draft.mime, size: draft.size }); const result = validateChatAttachment(file); if (result.error) { onError(result.error); return } if (recordingState !== "idle") clearRecording(); onSelect(draft.file); setMenuOpen(false) } catch (reason) { onError(reason instanceof Error ? reason.message : "附件信息无效。") } }
  useEffect(() => { const target = rootRef.current?.closest("section"); if (!target) return; const hasFiles = (event: DragEvent) => Array.from(event.dataTransfer?.types ?? []).includes("Files"); const enter = (event: DragEvent) => { if (!hasFiles(event)) return; event.preventDefault(); setDragging(true) }; const over = (event: DragEvent) => { if (!hasFiles(event)) return; event.preventDefault(); if (event.dataTransfer) event.dataTransfer.dropEffect = "copy" }; const leave = (event: DragEvent) => { if (event.currentTarget === event.target) setDragging(false) }; const drop = (event: DragEvent) => { if (!hasFiles(event)) return; event.preventDefault(); setDragging(false); const files = Array.from(event.dataTransfer?.files ?? []); if (files.length > 1) onError("当前一次只能发送一个附件。"); const file = files[0]; if (!file) return; try { logAttachmentFileDiagnostics("selected", file); const result = validateChatAttachment(file); if (result.error) { onError(result.error); return } const draft = createAttachmentDraft(file); logAttachmentFileDiagnostics("draft", file, { kind: draft.kind, name: draft.name, mime: draft.mime, size: draft.size }); onSelect(draft.file) } catch (reason) { onError(reason instanceof Error ? reason.message : "附件信息无效。") } }; target.addEventListener("dragenter", enter); target.addEventListener("dragover", over); target.addEventListener("dragleave", leave); target.addEventListener("drop", drop); return () => { target.removeEventListener("dragenter", enter); target.removeEventListener("dragover", over); target.removeEventListener("dragleave", leave); target.removeEventListener("drop", drop) } }, [onError, onSelect])
  const startRecording = async () => { if (!canRecordChatAudio(navigator.mediaDevices, typeof MediaRecorder === "undefined" ? undefined : MediaRecorder)) { onError("当前浏览器不支持语音录制，可选择上传音频文件。"); return } try { clearRecording(); const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream; const mime = ["audio/webm;codecs=opus", "audio/webm", "audio/ogg;codecs=opus", "audio/mp4"].find((value) => MediaRecorder.isTypeSupported(value)); if (!mime) { stopTracks(); onError("当前浏览器不支持语音录制，可选择上传音频文件。"); return } const recorder = new MediaRecorder(stream, { mimeType: mime }); recorderRef.current = recorder; chunksRef.current = []; recorder.ondataavailable = (event) => { if (event.data.size > 0) chunksRef.current.push(event.data) }; recorder.onerror = () => { stopTracks(); setRecordingState("idle"); onError("语音录制失败，请重试。") }; recorder.onstop = () => { stopTracks(); const recorderMimeType = recorder.mimeType || mime; const normalizedMime = normalizeMimeType(recorderMimeType) || normalizeMimeType(chunksRef.current[0]?.type ?? ""); const blob = new Blob(chunksRef.current, { type: normalizedMime }); chunksRef.current = []; if (!blob.size || !normalizedMime) { setRecordingState("idle"); onError("没有录到语音，请重试。"); return } const file = new File([blob], `语音-${Date.now()}.${extensionForMime(normalizedMime)}`, { type: normalizedMime }); setChatPreferredKind(file, "audio"); if (import.meta.env.DEV) console.info("[chat recording] completed", { recorderMimeType, blobType: blob.type, fileType: file.type, normalizedMime, detectedKind: "audio", extension: extensionForMime(normalizedMime), size: file.size }); const url = URL.createObjectURL(blob); previewUrlRef.current = url; setRecordedFile(file); setPreviewUrl(url); setRecordingState("recorded") }; recorder.start(); setSeconds(0); setRecordingState("recording"); setMenuOpen(false) } catch { stopTracks(); onError("无法使用麦克风，请检查浏览器授权。") } }
  const stopRecording = () => { if (recorderRef.current?.state === "recording") recorderRef.current.stop() }
  const sendRecording = () => { if (!recordedFile) return; setChatRecordingDuration(recordedFile, seconds); onSelect(recordedFile, { duration: seconds }); clearRecording() }
  return <div className="relative shrink-0" ref={rootRef}>{dragging && <div className="fixed inset-3 z-50 flex items-center justify-center rounded-3xl border-2 border-dashed border-primary bg-background/95 p-6 text-center text-sm font-semibold text-primary">松开发送文件</div>}{recordingState === "recording" ? <Button aria-label="停止录音" className="size-11" onClick={stopRecording} size="icon" type="button" variant="destructive"><Square /></Button> : <Button aria-label="添加附件" className="size-11" disabled={disabled} onClick={() => setMenuOpen((open) => !open)} size="icon" type="button" variant="secondary"><Paperclip /></Button>}{recordingState === "recording" && <span className="absolute right-0 -top-5 whitespace-nowrap text-[11px] text-destructive">正在录音 {String(Math.floor(seconds / 60)).padStart(2, "0")}:{String(seconds % 60).padStart(2, "0")}</span>}{recordingState === "recorded" && previewUrl && <div className="absolute bottom-12 left-0 z-30 w-56 rounded-2xl border bg-card p-3 shadow-md"><p className="text-xs font-semibold">语音已录制 {String(Math.floor(seconds / 60)).padStart(2, "0")}:{String(seconds % 60).padStart(2, "0")}</p><audio className="mt-2 w-full" controls preload="metadata" src={previewUrl} /><div className="mt-2 flex gap-2"><Button onClick={clearRecording} size="sm" type="button" variant="secondary"><RotateCcw />重录</Button><Button onClick={sendRecording} size="sm" type="button">发送</Button></div></div>}{menuOpen && <div className="absolute bottom-12 left-0 z-30 grid w-44 grid-cols-2 gap-1 rounded-2xl border bg-card p-2 shadow-md"><Button onClick={() => imageInput.current?.click()} size="sm" type="button" variant="ghost"><Image />图片</Button><Button onClick={() => fileInput.current?.click()} size="sm" type="button" variant="ghost"><FileIcon />文件</Button><Button onClick={() => videoInput.current?.click()} size="sm" type="button" variant="ghost"><Video />视频</Button><Button onClick={() => void startRecording()} size="sm" type="button" variant="ghost"><Mic />语音</Button></div>}<input accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" onChange={(event) => pick(event.target.files?.[0])} ref={imageInput} type="file" /><input accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip,audio/*" className="hidden" onChange={(event) => pick(event.target.files?.[0])} ref={fileInput} type="file" /><input accept="video/mp4,video/webm,video/quicktime" className="hidden" onChange={(event) => pick(event.target.files?.[0])} ref={videoInput} type="file" /></div>
}
