import { useEffect, useState, type FormEvent } from "react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"
import { fetchProfiles } from "@/lib/profiles"
import type { AdminTodo, AdminTodoDraft } from "@/types/adminTodo"
import type { Profile } from "@/types/auth"

export function AdminTodoFormSheet({ open, todo, onOpenChange, onSave }: { open: boolean; todo?: AdminTodo; onOpenChange: (open: boolean) => void; onSave: (draft: AdminTodoDraft) => Promise<void> }) {
  const [title, setTitle] = useState(todo?.title ?? ""); const [description, setDescription] = useState(todo?.description ?? ""); const [targetType, setTargetType] = useState<AdminTodoDraft["targetType"]>(todo?.targetType ?? "all"); const [targetCohort, setTargetCohort] = useState<2024 | 2025>(todo?.targetCohort ?? 2024); const [dueAt, setDueAt] = useState(todo?.dueAt ? todo.dueAt.slice(0, 16) : ""); const [profiles, setProfiles] = useState<Profile[]>([]); const [userIds, setUserIds] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  useEffect(() => { if (open && targetType === "users") void fetchProfiles().then(setProfiles).catch((reason) => setError(reason instanceof Error ? reason.message : "无法读取用户。")) }, [open, targetType])
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!title.trim()) { setError("请输入待办标题。"); return }; if (targetType === "users" && userIds.length === 0) { setError("请选择至少一位用户。"); return }; setSaving(true); try { await onSave({ title: title.trim(), description: description.trim() || null, dueAt: dueAt ? new Date(dueAt).toISOString() : null, targetType, targetCohort: targetType === "cohort" ? targetCohort : null, userIds }); onOpenChange(false) } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败。") } finally { setSaving(false) } }
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="bottom" className="responsive-bottom-sheet max-h-[92dvh] rounded-t-3xl"><SheetHeader><SheetTitle>{todo ? "编辑发布待办" : "发布待办"}</SheetTitle><SheetDescription>学院学习与事务提醒会按发送范围显示，个人完成状态互不影响。</SheetDescription></SheetHeader><form className="min-h-0 flex-1 space-y-4 overflow-y-auto px-4 pb-5" onSubmit={submit}><div><Label htmlFor="admin-todo-title">标题</Label><Input autoFocus className="mt-2 h-11" id="admin-todo-title" maxLength={120} onChange={(event) => setTitle(event.target.value)} value={title} /></div><div><Label htmlFor="admin-todo-description">说明</Label><Textarea className="mt-2" id="admin-todo-description" maxLength={2000} onChange={(event) => setDescription(event.target.value)} value={description} /></div><div><Label>发送给</Label><Select onValueChange={(value) => setTargetType(value as AdminTodoDraft["targetType"])} value={targetType}><SelectTrigger aria-label="发送范围" className="mt-2 h-11 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">全部同学</SelectItem><SelectItem value="cohort">按年级</SelectItem><SelectItem value="users">指定同学</SelectItem></SelectContent></Select></div>{targetType === "cohort" && <Select onValueChange={(value) => setTargetCohort(Number(value) as 2024 | 2025)} value={String(targetCohort)}><SelectTrigger aria-label="目标年级" className="h-11 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="2024">24级</SelectItem><SelectItem value="2025">25级</SelectItem></SelectContent></Select>}{targetType === "users" && <div className="space-y-2 rounded-2xl border p-3"><Label>指定同学</Label>{profiles.map((profile) => <label key={profile.id} className="flex min-h-11 items-center justify-between gap-2 text-sm"><span className="truncate">{profile.username} · {profile.cohortYear === 2024 ? "24级" : profile.cohortYear === 2025 ? "25级" : "未选年级"}</span><input checked={userIds.includes(profile.id)} className="size-4 accent-primary" onChange={(event) => setUserIds((ids) => event.target.checked ? [...ids, profile.id] : ids.filter((id) => id !== profile.id))} type="checkbox" /></label>)}</div>}<div><Label htmlFor="admin-todo-due">截止时间</Label><Input className="mt-2 h-11" id="admin-todo-due" onChange={(event) => setDueAt(event.target.value)} type="datetime-local" value={dueAt} /></div>{error && <p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive" role="alert">{error}</p>}<Button className="h-11 w-full" disabled={saving} type="submit">{saving ? "正在保存…" : todo ? "保存修改" : "发布待办"}</Button></form></SheetContent></Sheet>
}
