import { useState, type FormEvent } from "react"

import { AuthCard } from "@/components/auth/AuthCard"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { signUpWithPassword } from "@/lib/authService"
import { emailConfirmationInstructions, emailConfirmationRequiredMessage, registrationTutorialSteps } from "@/lib/registration"

export function RegisterPage({ onLogin }: { onLogin: () => void }) {
  const [username, setUsername] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("")
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [needsEmailConfirmation, setNeedsEmailConfirmation] = useState(false)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); setError(null); setMessage(null); setNeedsEmailConfirmation(false); try { const result = await signUpWithPassword(email.trim(), password, username.trim()); if (result.error) setError(result.error); else { const requiresConfirmation = result.needsEmailConfirmation === true; setNeedsEmailConfirmation(requiresConfirmation); setMessage(requiresConfirmation ? emailConfirmationRequiredMessage : "注册成功，正在进入课表。") } } catch (reason) { setError(reason instanceof Error ? reason.message : "注册失败。") } finally { setPending(false) } }
  return <AuthCard title="加入晴空课表" description="国际教育学院（中外合作办学）的校园学习生活小助手。所属年级决定年级聊天室和待办；课表仍可自由查看 24 / 25 级。"><form className="mt-6 space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="register-username">用户名</Label><Input autoComplete="nickname" id="register-username" maxLength={40} onChange={(event) => setUsername(event.target.value)} required value={username} /></div><div className="space-y-2"><Label htmlFor="register-email">邮箱</Label><Input autoComplete="email" id="register-email" onChange={(event) => setEmail(event.target.value)} required type="email" value={email} /></div><div className="space-y-2"><Label htmlFor="register-password">密码</Label><Input autoComplete="new-password" id="register-password" minLength={6} onChange={(event) => setPassword(event.target.value)} required type="password" value={password} /></div>{error && <p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive" role="alert">{error}</p>}{message && <div className="rounded-xl bg-primary/10 p-3 text-sm text-primary" role="status"><p>{message}</p>{needsEmailConfirmation && <><p className="mt-2 text-xs leading-5">{emailConfirmationInstructions}</p><Button className="mt-3 w-full" onClick={onLogin} type="button" variant="secondary">我已完成邮箱验证，去登录</Button></>}</div>}<Button className="h-11 w-full" disabled={pending} type="submit">{pending ? "正在注册…" : "注册"}</Button></form><section className="mt-4 rounded-2xl border border-border/70 bg-muted/35 p-3" aria-labelledby="registration-tutorial-title"><h2 className="text-sm font-semibold" id="registration-tutorial-title">注册教程</h2><ol className="mt-2 space-y-1 text-xs leading-5 text-muted-foreground">{registrationTutorialSteps.map((step, index) => <li key={step}>{`${index + 1}、${step}`}</li>)}</ol><p className="mt-2 rounded-xl bg-primary/10 px-2.5 py-2 text-xs leading-5 text-primary">注册后必须点击邮箱中的蓝色 Confirm email address，账号才会完成邮箱验证。</p></section><p className="mt-5 text-center text-sm text-muted-foreground">已有账号？<button className="ml-1 min-h-11 text-primary underline-offset-4 hover:underline" onClick={onLogin} type="button">去登录</button></p></AuthCard>
}
