import { useEffect, useMemo, useState } from "react"
import { Bookmark, Download, Flag, Plus, Quote, Search, Sparkles, UserRound, X } from "lucide-react"

import { PublishContributionSheet } from "@/components/learning/PublishContributionSheet"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"
import { useI18n } from "@/i18n/useI18n"
import { analyzeCourseCommons, fetchCourseContributions, filterCourseContributions, getContributionAssetUrl, getCourseCommonsMetrics, moderateContribution, quoteContributionToLearning, reportContribution, toggleContributionBookmark, unpublishContribution, updatePublishedContribution } from "@/lib/courseCommons"
import { useAuthStore } from "@/store/authStore"
import type { ContributionType, CourseCommonsAnalysis, CourseContribution } from "@/types/courseCommons"
import type { LearningRecord } from "@/types/learning"

type Filter = "all" | ContributionType

export function CourseCommonsPanel({ courseKey, courseName, onQuoted, records }: { courseKey: string; courseName: string; onQuoted: () => Promise<void>; records: readonly LearningRecord[] }) {
  const { locale, t } = useI18n(); const userId = useAuthStore((state) => state.user?.id ?? null); const role = useAuthStore((state) => state.profile?.role ?? "user")
  const [items, setItems] = useState<CourseContribution[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Filter>("all"); const [selected, setSelected] = useState<CourseContribution | null>(null); const [publishOpen, setPublishOpen] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [analysis, setAnalysis] = useState<CourseCommonsAnalysis | null>(null); const [analyzing, setAnalyzing] = useState(false); const [editing, setEditing] = useState(false); const [editTitle, setEditTitle] = useState(""); const [editContent, setEditContent] = useState("")
  useEffect(() => { let active = true; void fetchCourseContributions(courseKey).then((next) => { if (active) { setItems(next); setError(null) } }).catch(() => { if (active) setError(t("courseCommons.loadFailed")) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [courseKey, t])
  const visible = useMemo(() => filterCourseContributions(items, query, filter), [filter, items, query]); const metrics = getCourseCommonsMetrics(items)
  const open = (item: CourseContribution) => { setSelected(item); setEditTitle(item.title); setEditContent(item.content); setEditing(false) }
  const action = async (work: () => Promise<void>, message: string) => { try { await work(); setNotice(message); setError(null) } catch { setError(t("courseCommons.actionFailed")) } }
  const bookmark = async (item: CourseContribution) => action(async () => { await toggleContributionBookmark(item.id, item.bookmarked); setItems((all) => all.map((entry) => entry.id === item.id ? { ...entry, bookmarked: !entry.bookmarked, bookmarkCount: Math.max(0, entry.bookmarkCount + (entry.bookmarked ? -1 : 1)) } : entry)); setSelected((entry) => entry?.id === item.id ? { ...entry, bookmarked: !entry.bookmarked, bookmarkCount: Math.max(0, entry.bookmarkCount + (entry.bookmarked ? -1 : 1)) } : entry) }, t("courseCommons.bookmarkUpdated"))
  const quote = async (item: CourseContribution) => action(async () => { await quoteContributionToLearning(item.id); window.dispatchEvent(new Event("learning-records-changed")); await onQuoted() }, t("courseCommons.quoted"))
  const remove = async (item: CourseContribution) => action(async () => { await unpublishContribution(item.id); setItems((all) => all.filter((entry) => entry.id !== item.id)); setSelected(null) }, t("courseCommons.unpublished"))
  const saveEdit = async () => action(async () => { await updatePublishedContribution(selected!.id, editTitle, editContent, selected!.type); setItems((all) => all.map((item) => item.id === selected!.id ? { ...item, title: editTitle.trim(), content: editContent } : item)); setSelected((item) => item ? { ...item, title: editTitle.trim(), content: editContent } : item); setEditing(false) }, t("courseCommons.updated"))
  const runAnalysis = async () => { setAnalyzing(true); try { const result = await analyzeCourseCommons(courseKey); setAnalysis(result.analysis); setNotice(result.cached ? t("courseCommons.aiCached") : t("courseCommons.aiReady")) } catch { setError(t("courseCommons.aiFailed")) } finally { setAnalyzing(false) } }
  return <section className="course-commons"><header className="course-commons__header"><div><p>COURSE COMMONS</p><h2>{courseName}</h2><span>{metrics.contributions} {t("courseCommons.contributions")} · {metrics.contributors} {t("courseCommons.contributors")}</span></div><div><Button onClick={() => setPublishOpen(true)}><Plus className="size-4" />{t("courseCommons.shareFirst")}</Button><Button disabled={analyzing || !items.length} onClick={() => void runAnalysis()} variant="outline"><Sparkles className="size-4" />{t("courseCommons.aiOrganize")}</Button></div></header>
    <div className="course-commons__tools"><label><Search className="size-4" /><Input aria-label={t("courseCommons.search")} onChange={(event) => setQuery(event.target.value)} placeholder={t("courseCommons.search")} value={query} /></label><nav aria-label={t("courseCommons.filter")}>{(["all", "note", "knowledge", "resource"] as const).map((item) => <button aria-pressed={filter === item} data-active={filter === item} key={item} onClick={() => setFilter(item)} type="button">{t(`courseCommons.filter${item[0].toUpperCase()}${item.slice(1)}` as "courseCommons.filterAll")}</button>)}</nav></div>
    {notice ? <p className="learning-inline-notice" role="status">{notice}</p> : null}{error ? <p className="learning-inline-error" role="alert">{error}</p> : null}
    {analysis ? <article className="course-commons__analysis"><div><Sparkles className="size-4" /><strong>{t("courseCommons.aiOverview")}</strong><button aria-label={t("common.close")} onClick={() => setAnalysis(null)} type="button"><X className="size-4" /></button></div><p>{analysis.courseSummary}</p><ul>{analysis.keyTopics.map((topic) => <li key={topic}>{topic}</li>)}</ul><small>{t("courseCommons.aiAssisted")}</small></article> : null}
    {loading ? <p className="course-commons__empty">{t("common.loading")}</p> : visible.length ? <div className="course-commons__feed">{visible.map((item) => <article key={item.id}><time>{new Intl.DateTimeFormat(locale, { month: "2-digit", day: "2-digit" }).format(new Date(item.publishedAt))}</time><button onClick={() => open(item)} type="button"><span>{t(`courseCommons.type${item.type[0].toUpperCase()}${item.type.slice(1)}` as "courseCommons.typeNote")} · {item.authorName}</span><h3>{item.title}</h3><p>{item.content || item.aiSummary || t("courseCommons.attachmentContribution")}</p><small>{item.aiKeyPoints.length} {t("courseCommons.keyPoints")} · {item.assets.length} {t("courseCommons.attachments")} · {item.bookmarkCount} {t("courseCommons.bookmarks")}</small></button></article>)}</div> : <div className="course-commons__empty"><p>{query ? t("courseCommons.searchEmpty") : t("courseCommons.empty")}</p>{!query ? <Button onClick={() => setPublishOpen(true)} variant="outline">{t("courseCommons.shareFirst")}</Button> : null}</div>}
    <PublishContributionSheet courseKey={courseKey} onOpenChange={setPublishOpen} onPublished={(item) => { setItems((all) => [item, ...all]); setNotice(t("courseCommons.published")) }} open={publishOpen} records={records} />
    <Sheet onOpenChange={(value) => { if (!value) setSelected(null) }} open={Boolean(selected)}><SheetContent className="course-commons-detail" side="right">{selected ? <><SheetHeader><SheetTitle>{selected.title}</SheetTitle><SheetDescription>{selected.courseName} · {selected.authorName}</SheetDescription></SheetHeader><div className="course-commons-detail__body">{editing ? <><Input maxLength={160} onChange={(event) => setEditTitle(event.target.value)} value={editTitle} /><Textarea className="min-h-56" maxLength={30000} onChange={(event) => setEditContent(event.target.value)} value={editContent} /><Button onClick={() => void saveEdit()}>{t("common.save")}</Button></> : <><p>{selected.content}</p>{selected.aiSummary ? <section><strong>{t("courseCommons.aiAssisted")}</strong><p>{selected.aiSummary}</p><ul>{selected.aiKeyPoints.map((point) => <li key={point}>{point}</li>)}</ul></section> : null}{selected.assets.map((asset) => <button className="course-commons-asset" key={asset.id} onClick={() => void getContributionAssetUrl(asset).then((url) => window.open(url, "_blank", "noopener,noreferrer"))} type="button"><Download className="size-4" /><span>{asset.fileName}</span></button>)}</>}
      <div className="course-commons-detail__actions"><Button onClick={() => void bookmark(selected)} variant="outline"><Bookmark className="size-4" />{t(selected.bookmarked ? "courseCommons.unbookmark" : "courseCommons.bookmark")}</Button><Button onClick={() => void quote(selected)} variant="outline"><Quote className="size-4" />{t("courseCommons.quote")}</Button><Button onClick={() => void action(() => reportContribution(selected.id, "other"), t("courseCommons.reported"))} variant="ghost"><Flag className="size-4" />{t("courseCommons.report")}</Button>{selected.authorId === userId ? <><Button onClick={() => setEditing(true)} variant="ghost">{t("courseCommons.editPublic")}</Button><Button onClick={() => void remove(selected)} variant="destructive">{t("courseCommons.unpublish")}</Button></> : null}{(role === "admin" || role === "super_admin") && selected.authorId !== userId ? <Button onClick={() => void action(async () => { await moderateContribution(selected.id, "hide"); setItems((all) => all.filter((item) => item.id !== selected.id)); setSelected(null) }, t("courseCommons.hidden"))} variant="destructive">{t("courseCommons.hide")}</Button> : null}</div><footer><UserRound className="size-4" />{t("courseCommons.sourceAttribution").replace("{author}", selected.authorName).replace("{course}", selected.courseName)}</footer></div></> : null}</SheetContent></Sheet>
  </section>
}
